<?php

/**
 * @file
 * Code for the Filtered Videos feature.
 */

include_once 'filtered_videos.features.inc';

/**
 * Implements hook_theme().
 */
function filtered_videos_theme($existing, $type, $theme, $path) {
  // Override node.tpl.php.
  return array(
    'node__filtered_videos' => array(
      'render element' => 'content',
      'base hook' => 'node',
      'template' => 'node--filtered_videos',
      'path' => drupal_get_path('module', 'filtered_videos') . '/templates',
    ),
  );
}

/**
 * Implements hook_node_view().
 */
function filtered_videos_node_view($node, $view_mode, $langcode) {
  // Attach JS and settings.
  if ($view_mode == 'full') {
    if ($node->type == 'filtered_videos') {
      $fields = array();
      $fields['auto'] = $node->field_auto_fetch[$node->language][0]['value'];
      $fields['school'] = $node->field_school[$node->language][0]['value'];
      $fields['sport'] = $node->field_sport[$node->language][0]['value'];
      $node->content['#attached']['js'][] = array(
        'type' => 'setting',
        'data' => array(
          'filtered_videos' => $fields,
        ),
      );
      $node->content['#attached']['js'][] = array(
        'type' => 'file',
        'data' => drupal_get_path('module', 'filtered_videos') . '/js/filtered-videos.js',
      );
    }
  }
}
